#ifndef PROGRAMSETTINGS_H
#define PROGRAMSETTINGS_H

#include <QtGlobal>

// ALL THE GLOBAL DECLARATIONS

QT_BEGIN_NAMESPACE
class QString;
QT_END_NAMESPACE

extern QString g_username;

#endif // PROGRAMSETTINGS_H
